### ISSUE TITLE
Searching does not work

### ISSUE THREAD

**Issue by aardschok** [Colorbleed/scriptsmenu#13]
# Problem
When typing a keyword in the search bar the menu items are not shown, only the sub menus.

**Comment by BigRoy** [comment]
Actually, this is working for me. What's **not** working is hiding the submenus when it has no children menu items that match the search.

So the menu items are actually shown correctly.

**Comment by aardschok** [comment]
## update
When typing a keyword not present like, `animi` in stead of `anim` none show, which is correct but when altering the word, the scriptsmenu does not update its search result.
It looks like the widget does not recognize the backspace as an input to trigger `textChanged`
