### ISSUE TITLE
Implementing ScriptMenu in a standalone qt interface -> ScriptMenu standard behaviour is to hide itself

### ISSUE THREAD

**Issue by BenoitConnan** [Colorbleed/scriptsmenu#16]
Hello,

I'm trying to implement kind of a "launchforqt.py" for softs with unextendable menus (ie: photoshop)
Yet i've encoutered some difficulty doing so. Scriptmenu implements very well with qt but each time
I click somewhere else in the scriptmenu, it seems to hide itself.
Is it a intended behaviour of ScriptMenu ? Does anybody know why and where and if it's possible to bypass this behaviour ?

![image](https://user-images.githubusercontent.com/82808268/150505049-388faf29-3207-4f59-abea-a26dc55c1545.png)
 /mouse click/
![image](https://user-images.githubusercontent.com/82808268/150505124-fe0e0e27-237b-49bc-959b-1c869232b8c1.png)

**Comment by BenoitConnan** [comment]
Urrrgh my bad, didn't pay attenttion, it's a QMenu behaviour

**Comment by BigRoy** [comment]
@BenoitConnan what's the exact behavior you are after instead? Would you like to use it as a pop-up that remains open?

**Comment by BenoitConnan** [comment]
> @BenoitConnan what's the exact behavior you are after instead? Would you like to use it as a pop-up that remains open?

That exactly what i'm trying to do. Instead of a menu i launch a qapp with a photoshop extension (the one in the screenshots)
